In [1]:
import numpy as np

In [2]:
my_list1 = [1,2,3,4]
my_list2 = [5,6,7,8]
my_array = np.array([my_list1, my_list2])
print(my_array)

[[1 2 3 4]
 [5 6 7 8]]


In [3]:
print(my_array.shape)
print(my_array.dtype)
print(type(my_array))

(2, 4)
int32
<class 'numpy.ndarray'>


In [4]:
my_array_zeros = np.zeros(5)
print(my_array_zeros)

[0. 0. 0. 0. 0.]


In [5]:
my_array_ones = np.ones([5,5])
print(my_array_ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
my_array_empty = np.empty(5) 
print(my_array_empty)

[0. 0. 0. 0. 0.]


In [7]:
my_array_identity = np.eye(5)
print(my_array_identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
my_array_arange = np.arange(10,100,3)
print(my_array_arange)

[10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70 73 76 79
 82 85 88 91 94 97]


In [9]:
my_array_add = my_array + my_array
print(my_array_add)

[[ 2  4  6  8]
 [10 12 14 16]]


In [10]:
my_array_subtract = my_array - my_array
print(my_array_subtract)

[[0 0 0 0]
 [0 0 0 0]]


In [11]:
my_array_multiply = my_array*my_array
print(my_array_multiply)

[[ 1  4  9 16]
 [25 36 49 64]]


In [12]:
my_array_divide = my_array/my_array
print(my_array_divide)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
my_array_resiprocal = 1/my_array
print(my_array_resiprocal)

[[1.         0.5        0.33333333 0.25      ]
 [0.2        0.16666667 0.14285714 0.125     ]]


In [14]:
my_array_power = my_array**3
print(my_array_power)

[[  1   8  27  64]
 [125 216 343 512]]


In [15]:
my_array_copy = my_array.copy()
print(my_array_copy)

[[1 2 3 4]
 [5 6 7 8]]


In [16]:
# Indexing
multi_array = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(multi_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
# Accessing rows and columns

# Zeroth row
print(multi_array[0, :])
# Alternate
# print(multi_array[0]) 

# Zeroth column
print(multi_array[: ,0])

# Zeroth row and zeroth column
print(multi_array[0,0])

[1 2 3]
[1 4 7]
1


In [18]:
# Slicing
print(multi_array[0:2, 1:2])  # i.e. 0th to 1st row and 1st column

# Alternate for only rows
# print(multi_array[[0,1]])

[[2]
 [5]]


In [19]:
# Assigning 
multi_array[0:2,1:2] = 73
print(multi_array)

[[ 1 73  3]
 [ 4 73  6]
 [ 7  8  9]]


In [20]:
# Looping and accessing
nrow = multi_array.shape[0]
ncol = multi_array.shape[1]

for i in range(nrow):
    for j in range(ncol):
        print(multi_array[i][j])

1
73
3
4
73
6
7
8
9


In [21]:
# Sum of elements
print(multi_array.sum())

# Product of elements
print(multi_array.prod())

# Mean of elements
print(multi_array.mean())

# Standard deviation of elements
print(multi_array.std())

# Variance of elements
print(multi_array.var())

# Column sums
print(multi_array.sum(0))

184
193378752
20.444444444444443
28.19027062702115
794.6913580246913
[ 12 154  18]


In [22]:
# Looping in increments
a = np.arange(1,20,2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


In [23]:
# Square-root of array elements
print(np.sqrt(a))

# Exponential of array elements
print(np.exp(a))

# Maximum of array elements
print(np.max(a))

# Minimum of array elements
print(np.min(a))

# Sum of array elements
print(np.sum(a))
# Alternatively
# print(a.sum())

# Product of array elemets
print(np.prod(a))
# Alternatively
# print(a.prod())

[1.         1.73205081 2.23606798 2.64575131 3.         3.31662479
 3.60555128 3.87298335 4.12310563 4.35889894]
[2.71828183e+00 2.00855369e+01 1.48413159e+02 1.09663316e+03
 8.10308393e+03 5.98741417e+04 4.42413392e+05 3.26901737e+06
 2.41549528e+07 1.78482301e+08]
19
1
100
654729075


In [24]:
MyArray = np.array([45,87,12,34,74,45,78,12,74])

# Soring array
print(np.sort(MyArray))

# Finding unique elements
print(np.unique(MyArray))

# Finding if elements in array
print(np.in1d([56,12], MyArray))

[12 12 34 45 45 74 74 78 87]
[12 34 45 74 78 87]
[False  True]


In [25]:
# Array operations using built in functions
a1 = np.array([1,2,3])
a2 = np.array([3,1,2])

# Adding arrays
print(np.add(a1,a2))

# Subtracting arrays
print(np.subtract(a1,a2))

# Multiplying arrays
print(np.multiply(a1,a2))

# Dividing arrays
print(np.divide(a1,a2))

[4 3 5]
[-2  1  1]
[3 2 6]
[0.33333333 2.         1.5       ]


In [26]:
# Maximum of both positions
print(np.maximum(a1,a2))

# Minimum of both positons
print(np.minimum(a1,a2))

[3 2 3]
[1 1 2]


In [27]:
# Saving and loading an array from external memory
array = np.array([1,2,3,4,5,6,7])
np.save("saved_array.npy", array)
loaded_array = np.load("saved_array.npy")
print(loaded_array)

[1 2 3 4 5 6 7]


In [28]:
# Saving and loading arrays from external memory
arr0 = np.array([1,2,3,4,5,6,7])
arr1 = np.array([9,8,7,6,5,4,3])
np.savez("saved_archive.npz", a0 = arr0, a1 = arr1)
loaded_archive = np.load("saved_archive.npz")
print(loaded_archive["a0"])
print(loaded_archive["a1"])

[1 2 3 4 5 6 7]
[9 8 7 6 5 4 3]


In [29]:
# Saving to textfile
array = np.array([1,2,3,4,5,6,7])
np.savetxt("textfile.txt", array, delimiter = ",")
loaded_text = np.loadtxt("textfile.txt", delimiter = ",")
print(loaded_text)

[1. 2. 3. 4. 5. 6. 7.]


In [30]:
# Statistical and Mathemaical Processing
import matplotlib.pyplot as plt

axis_values = np.arange(-100, 100, 10)
x, y = np.meshgrid(axis_values, axis_values)
f = 2*x + 3*y
print(plt.imshow(f))
plt.title("Plot of f = 2x + 3y")
plt.colorbar()
plt.savefig("MyPic.png")

AxesImage(80,52.8;496x369.6)


In [31]:
# Conditional clauses and boolean operations
x = np.array([100,200,300,400,500])
y = np.array([500,70, 23, 600, 15])
conditions = np.array([True, False, True, False, False])

z1  = [a if cond else b for a,cond,b in zip(x,conditions,y)]
print(z1)

z2 = np.where(conditions, x, y)
print(z2)

z3 = np.where(x>350, 1, 0)
print(z3)

# "OR" of elements
print(conditions.any())

# "AND" of elements
print(conditions.all())

[100, 70, 300, 600, 15]
[100  70 300 600  15]
[0 0 0 1 1]
True
False
